[2025-01-02T20:04:19.205+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T20:04:19.233+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2025-01-02T20:03:41.987678+00:00 [queued]>
[2025-01-02T20:04:19.249+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2025-01-02T20:03:41.987678+00:00 [queued]>
[2025-01-02T20:04:19.251+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-02T20:04:19.279+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_orders> on 2025-01-02 20:03:41.987678+00:00
[2025-01-02T20:04:19.293+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=499) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-02T20:04:19.295+0000] {standard_task_runner.py:72} INFO - Started process 501 to run task
[2025-01-02T20:04:19.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_dim_orders', 'manual__2025-01-02T20:03:41.987678+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmp2dow85mn']
[2025-01-02T20:04:19.297+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask etl_dim_orders
[2025-01-02T20:04:19.370+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_dim_orders manual__2025-01-02T20:03:41.987678+00:00 [running]> on host 70b53016fb73
[2025-01-02T20:04:19.496+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_dim_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T20:03:41.987678+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T20:03:41.987678+00:00'
[2025-01-02T20:04:19.498+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T20:10:20.689+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T20:10:20.700+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T20:10:20.701+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_dim_orders, run_id=manual__2025-01-02T20:03:41.987678+00:00, execution_date=20250102T200341, start_date=20250102T200419, end_date=20250102T201020
[2025-01-02T20:10:20.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T20:10:20.786+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-02T20:10:20.791+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
