[2024-12-03T20:03:59.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T20:03:59.251+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl_pipeline.generate_dim_date manual__2024-12-03T20:03:44.215895+00:00 [queued]>
[2024-12-03T20:03:59.264+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl_pipeline.generate_dim_date manual__2024-12-03T20:03:44.215895+00:00 [queued]>
[2024-12-03T20:03:59.406+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-03T20:04:02.089+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_dim_date> on 2024-12-03 20:03:44.215895+00:00
[2024-12-03T20:04:02.162+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T20:04:02.165+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl_pipeline', 'generate_dim_date', 'manual__2024-12-03T20:03:44.215895+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmp2oczblg6']
[2024-12-03T20:04:02.166+0000] {standard_task_runner.py:72} INFO - Started process 332 to run task
[2024-12-03T20:04:02.173+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask generate_dim_date
[2024-12-03T20:04:02.308+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl_pipeline.generate_dim_date manual__2024-12-03T20:03:44.215895+00:00 [running]> on host 40a20da4c799
[2024-12-03T20:04:02.611+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl_pipeline' AIRFLOW_CTX_TASK_ID='generate_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T20:03:44.215895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T20:03:44.215895+00:00'
[2024-12-03T20:04:02.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T20:04:02.692+0000] {base.py:84} INFO - Retrieving connection 'mssql_default'
[2024-12-03T20:04:03.085+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T20:04:03.109+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T20:04:03.111+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl_pipeline, task_id=generate_dim_date, run_id=manual__2024-12-03T20:03:44.215895+00:00, execution_date=20241203T200344, start_date=20241203T200359, end_date=20241203T200403
[2024-12-03T20:04:03.192+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T20:04:03.231+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T20:04:03.242+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
