[2025-01-01T21:22:18.323+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T21:22:18.348+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2025-01-01T21:22:18.362+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2025-01-01T21:22:18.363+0000] {taskinstance.py:2866} INFO - Starting attempt 11 of 11
[2025-01-01T21:22:18.383+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_fact_instacart> on 2024-12-26 15:23:11.859664+00:00
[2025-01-01T21:22:18.402+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11560) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-01T21:22:18.401+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_fact_instacart', 'manual__2024-12-26T15:23:11.859664+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmpl90piofp']
[2025-01-01T21:22:18.405+0000] {standard_task_runner.py:72} INFO - Started process 11562 to run task
[2025-01-01T21:22:18.406+0000] {standard_task_runner.py:105} INFO - Job 304: Subtask etl_fact_instacart
[2025-01-01T21:22:18.465+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [running]> on host e3ff7ec590df
[2025-01-01T21:22:18.587+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_fact_instacart' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T15:23:11.859664+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T15:23:11.859664+00:00'
[2025-01-01T21:22:18.590+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T21:22:44.210+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-01T21:22:44.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T21:22:44.234+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_fact_instacart, run_id=manual__2024-12-26T15:23:11.859664+00:00, execution_date=20241226T152311, start_date=20250101T212218, end_date=20250101T212244
[2025-01-01T21:22:44.312+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-01T21:22:44.333+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T21:22:44.337+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
