[2024-12-17T12:52:53.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T12:52:53.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-17T12:32:35.428480+00:00 [queued]>
[2024-12-17T12:52:53.066+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-17T12:32:35.428480+00:00 [queued]>
[2024-12-17T12:52:53.067+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-17T12:52:53.088+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_orders> on 2024-12-17 12:32:35.428480+00:00
[2024-12-17T12:52:53.108+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6428) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-17T12:52:53.113+0000] {standard_task_runner.py:72} INFO - Started process 6435 to run task
[2024-12-17T12:52:53.113+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_dim_orders', 'manual__2024-12-17T12:32:35.428480+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmpv40_ii4v']
[2024-12-17T12:52:53.117+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask etl_dim_orders
[2024-12-17T12:52:53.227+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-17T12:32:35.428480+00:00 [running]> on host ad3472fa3861
[2024-12-17T12:52:53.389+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_dim_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T12:32:35.428480+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T12:32:35.428480+00:00'
[2024-12-17T12:52:53.391+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T13:13:40.171+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-17T13:13:40.654+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T13:13:40.669+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_dim_orders, run_id=manual__2024-12-17T12:32:35.428480+00:00, execution_date=20241217T123235, start_date=20241217T125253, end_date=20241217T131340
[2024-12-17T13:13:40.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-17T13:13:41.271+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-17T13:13:41.277+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
