[2024-12-05T15:10:20.349+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T15:10:20.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_department manual__2024-12-05T15:10:18.726273+00:00 [queued]>
[2024-12-05T15:10:20.377+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_department manual__2024-12-05T15:10:18.726273+00:00 [queued]>
[2024-12-05T15:10:20.379+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T15:10:20.396+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_department> on 2024-12-05 15:10:18.726273+00:00
[2024-12-05T15:10:20.413+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-05T15:10:20.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_dim_department', 'manual__2024-12-05T15:10:18.726273+00:00', '--job-id', '520', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpva5z0k58']
[2024-12-05T15:10:20.415+0000] {standard_task_runner.py:72} INFO - Started process 358 to run task
[2024-12-05T15:10:20.416+0000] {standard_task_runner.py:105} INFO - Job 520: Subtask etl_dim_department
[2024-12-05T15:10:20.480+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_dim_department manual__2024-12-05T15:10:18.726273+00:00 [running]> on host a2b0a234d4c4
[2024-12-05T15:10:20.585+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_dim_department' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T15:10:18.726273+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T15:10:18.726273+00:00'
[2024-12-05T15:10:20.588+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T15:10:20.631+0000] {base.py:84} INFO - Retrieving connection 'mssql_default'
[2024-12-05T15:10:20.861+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T15:10:20.879+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T15:10:20.880+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_dim_department, run_id=manual__2024-12-05T15:10:18.726273+00:00, execution_date=20241205T151018, start_date=20241205T151020, end_date=20241205T151020
[2024-12-05T15:10:20.955+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T15:10:20.992+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T15:10:20.996+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
