[2024-12-05T03:35:08.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T03:35:09.002+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl_pl.etl_dim_department manual__2024-12-05T03:35:07.233424+00:00 [queued]>
[2024-12-05T03:35:09.010+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl_pl.etl_dim_department manual__2024-12-05T03:35:07.233424+00:00 [queued]>
[2024-12-05T03:35:09.011+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T03:35:09.034+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_department> on 2024-12-05 03:35:07.233424+00:00
[2024-12-05T03:35:09.043+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3576) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-05T03:35:09.044+0000] {standard_task_runner.py:72} INFO - Started process 3586 to run task
[2024-12-05T03:35:09.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl_pl', 'etl_dim_department', 'manual__2024-12-05T03:35:07.233424+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmpiadq3z4z']
[2024-12-05T03:35:09.050+0000] {standard_task_runner.py:105} INFO - Job 413: Subtask etl_dim_department
[2024-12-05T03:35:09.106+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl_pl.etl_dim_department manual__2024-12-05T03:35:07.233424+00:00 [running]> on host 58313fa44d8d
[2024-12-05T03:35:09.206+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl_pl' AIRFLOW_CTX_TASK_ID='etl_dim_department' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T03:35:07.233424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T03:35:07.233424+00:00'
[2024-12-05T03:35:09.207+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T03:35:09.233+0000] {base.py:84} INFO - Retrieving connection 'mssql_default'
[2024-12-05T03:35:09.287+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T03:35:09.297+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T03:35:09.298+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl_pl, task_id=etl_dim_department, run_id=manual__2024-12-05T03:35:07.233424+00:00, execution_date=20241205T033507, start_date=20241205T033509, end_date=20241205T033509
[2024-12-05T03:35:09.342+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T03:35:09.364+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T03:35:09.370+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
