[2024-12-11T17:32:57.027+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T17:32:57.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl_test.etl_dim_user manual__2024-12-11T17:32:50.418382+00:00 [queued]>
[2024-12-11T17:32:57.051+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl_test.etl_dim_user manual__2024-12-11T17:32:50.418382+00:00 [queued]>
[2024-12-11T17:32:57.052+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-11T17:32:57.066+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_user> on 2024-12-11 17:32:50.418382+00:00
[2024-12-11T17:32:57.080+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5392) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-11T17:32:57.081+0000] {standard_task_runner.py:72} INFO - Started process 5394 to run task
[2024-12-11T17:32:57.080+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl_test', 'etl_dim_user', 'manual__2024-12-11T17:32:50.418382+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/test_etl_dag.py', '--cfg-path', '/tmp/tmplj9dwv2s']
[2024-12-11T17:32:57.083+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask etl_dim_user
[2024-12-11T17:32:57.133+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl_test.etl_dim_user manual__2024-12-11T17:32:50.418382+00:00 [running]> on host 2ccb08007d56
[2024-12-11T17:32:57.243+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl_test' AIRFLOW_CTX_TASK_ID='etl_dim_user' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T17:32:50.418382+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T17:32:50.418382+00:00'
[2024-12-11T17:32:57.244+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T17:32:57.275+0000] {base.py:84} INFO - Retrieving connection 'mssql_default'
[2024-12-11T17:35:34.544+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-11T17:35:34.555+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T17:35:34.556+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl_test, task_id=etl_dim_user, run_id=manual__2024-12-11T17:32:50.418382+00:00, execution_date=20241211T173250, start_date=20241211T173257, end_date=20241211T173534
[2024-12-11T17:35:34.615+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T17:35:34.642+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-11T17:35:34.648+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
