[2024-12-26T15:28:06.145+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T15:28:06.171+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2024-12-26T15:28:06.185+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2024-12-26T15:28:06.185+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-26T15:28:06.206+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_orders> on 2024-12-26 15:23:11.859664+00:00
[2024-12-26T15:28:06.220+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T15:28:06.222+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2024-12-26T15:28:06.220+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_dim_orders', 'manual__2024-12-26T15:23:11.859664+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmp_hztuor3']
[2024-12-26T15:28:06.223+0000] {standard_task_runner.py:105} INFO - Job 292: Subtask etl_dim_orders
[2024-12-26T15:28:06.291+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_dim_orders manual__2024-12-26T15:23:11.859664+00:00 [running]> on host e3ff7ec590df
[2024-12-26T15:28:06.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_dim_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T15:23:11.859664+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T15:23:11.859664+00:00'
[2024-12-26T15:28:06.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T15:34:21.480+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-26T15:34:21.620+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T15:34:21.623+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_dim_orders, run_id=manual__2024-12-26T15:23:11.859664+00:00, execution_date=20241226T152311, start_date=20241226T152806, end_date=20241226T153421
[2024-12-26T15:34:21.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-26T15:34:22.252+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26T15:34:22.257+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
